### ISSUE TITLE
Add ability to estimate amount of rewards earned by user between harvesting cycles

### ISSUE THREAD

**Issue by 0xtuytuy** [GetAlluo/liquidity-direction-protocol#108]
**Is your feature request related to a problem? Please describe.**
Today, there is no way for a user to know how many rewards he has pending since the last harvest cycle. This could lead to him exiting the pool on day 6 of the harvest cycle and therefore losing all his pending rewards rather than waiting one day and getting the full rewards he has earned. 

**Describe the solution you'd like**
TBD but the goal is to have a view function that would allow the FE to view how many rewards are pending so we can display this info to the user.

**Describe alternatives you've considered**
No real alternative

**Additional context**
NA

**Comment by pentatonictritones** [comment]
separate in yieldbooster
