### ISSUE TITLE
[Polygon] Superfluid implementation for IbAlluo

### ISSUE THREAD

**Issue by 0xtuytuy** [GetAlluo/liquidity-direction-protocol#38]
### Summary

1. Name: Superfluid implementation for IbAlluo
2. About: Implement the ability to stream IbAlluo tokens to a destination address using the superfluid API

### Is your proposal related to a problem?

No problem, just enabling the protocol 

### Describe the solution you'd like

The idea here would be to be able to stream IbAlluo tokens from one address to another using the CFA library from superfluid. The greater picture is that this would allow ppl to borrow against a Stream to be money in advance for free because we would use the Interest of the token to pay the protocol and the lender (person funding the stream).

There are really 4 main things to do:
- Convert the IbAlluo interface into a StreamingIntersetBearingAlluo token (StIbAlluo)
- Implement the Constant Flow Agreement wrapper for the StIbAlluoXXX tokens
- Implement the StIbAlluo interface in the IbAlluoUSD

The StIbAlluo will need to follow the Super standard described here by Superfluid: https://docs.superfluid.finance/superfluid/protocol-developers/super-tokens 

The challenge however is that we want the StIbAlluo to be backwards compatible with ERC20 and with the older IbAlluo. We should therefore have the option to use the streaming functionality or not. This is to enable the mobile app users to choose this feature or not.

**Comment by hellwolf** [comment]
Looking forward to!

**Comment by 0xtuytuy** [comment]
This is live and already used by the @ricochet exchange team for DCA markets.
